owner: loongwork
repo: status

sites:
  - name: Official Website
    url: https://www.loongwork.net
  - name: Minecraft Main Server
    check: "tcp-ping"
    url: $MC_MAIN_URL
    port: $MC_MAIN_PORT
  - name: Minecraft Proxy
    check: "tcp-ping"
    url: $MC_PROXY_URL
    port: $MC_PROXY_PORT

status-website:
  cname: status.loongwork.net
  logoUrl: https://cdn.loongwork.net/front/logo.png
  name: LoongWork Services Status
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
